spring:
  jackson:
    mapper:
      accept_case_insensitive_properties: true
  project: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: postgres
    password: developer
    diverClassName: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
logging:
  level:
    root: INFO